### ISSUE TITLE
Referencing 'git' package twice

### ISSUE THREAD

**Issue by JasonKAls** [aws-quickstart/quickstart-awx#17]
https://github.com/aws-quickstart/quickstart-awx/blob/4191f6531f1cf33059f4d202a1c381930c9b3c17/templates/awx.template#L187

I'm sure it doesn't impact anything. Just FYI.

**Comment by carthewd** [comment]
Good catch, thanks for calling that out... I've submitted a PR to clean it up

**Comment by JasonKAls** [comment]
No prob ;)

**Comment by gargana** [comment]
#18 Merged into master
