### ISSUE TITLE
Change of awx version fails the deployment

### ISSUE THREAD

**Issue by Harshal-20** [aws-quickstart/quickstart-awx#19]
Is it possible to allow change in awx version for this deployment?

**Comment by gargana** [comment]
Hi Harshal

Can you share some detail around how you encountered the failure and any specific error messages you are seeing in the CloudFormation stacks and the nested stacks?
Which specific resource is failing?
Are you using a customized version of the QuickStart templates?

Thanks

**Comment by jagibson** [comment]
The AWXVersion allowed in the templates only allows versions 1.0.0 and 1.0.1.  These are both very old.  The latest is 4.0.0 at this time.

You can modify AWXVersion AllowedValues in awx.template and awx-workload.template but this breaks other things with this quickstart template.

**Comment by gargana** [comment]
Hi Harshal

I have updated the QuickStart to support newer versions and am working on automating testing and inclusion of newer versions of AWX as they become available.

Please be aware that simply changing the version may be a really bad idea if their are incompatibilities between the versions and if there are not migrations in place for the DB backend.

I would recommend installing a second copy with the new version desired and migrating the configuration across. 

Please take a look here: https://github.com/ansible/awx/issues/2225
