### ISSUE TITLE
quickstart-awx has good intentions but is outdated and badly needs features

### ISSUE THREAD

**Issue by jagibson** [aws-quickstart/quickstart-awx#20]
I was very hopeful that this would allow me to build an AWX environment quickly but there's just too many things that are not working.

- The latest version of AWX it supports (1.0.1) is from October 2017.  The current version is 4.0.0
- Newer versions of AWX will not work even if you change the AllowedValues for AWXVersion
- Incomplete support for existing RDS instances
- Incomplete support for existing ECS clusters
- Incomplete support for existing ALBs
- ALB creation does not have an option for internal-only

It seems like this project is only getting the most minimal support.

**Comment by gargana** [comment]
I will be working on updating this to support new versions. I may also split off some of the list above as their own separate issues to track work against.

**Comment by jagibson** [comment]
@gargana Cool beans.  I didn't mean to sound ungrateful  - I was just frustrated at the amount of time I sunk into it before changing tack to a different solution.

**Comment by gargana** [comment]
@jagibson all good :). I should have a PR ready soon to enable all release versions going forward.
Are there any other Quality of Life improvements you can think of which would make using the QS easier, other than the issues mentioned before.

**Comment by jagibson** [comment]
@gargana Sorry for the late response.  The only other thing I can remember was that I needed the ability to change the TemplateURLs - useful if you need to modify a template and put it in your own S3 bucket.

**Comment by posthum** [comment]
Are we getting close to adding support for AWX 4.0.0 to this quickstart? I spent quite a bit of time trying to get it working with 4.0.0 (web interface to AWX returns 501 error constantly) before being forced to fall back to 3.0.1. Many thanks!

**Comment by gargana** [comment]
I am currently taking a look into this

**Comment by gargana** [comment]
> @gargana Sorry for the late response. The only other thing I can remember was that I needed the ability to change the TemplateURLs - useful if you need to modify a template and put it in your own S3 bucket.
@jagibson I do this specifically for my own testing, the parameters QSS3BucketName and QSS3KeyPrefix allow you to specify your own bucket for the templates and the bucket prefix under which the templates can be found. Let me know if this helps or if I have missed something?

**Comment by jagibson** [comment]
@gargana IIRC changing QSS3BucketName and QSS3KeyPrefix are not enough for using your own S3 bucket.  Could be wrong tho.

**Comment by gargana** [comment]
> @gargana IIRC changing QSS3BucketName and QSS3KeyPrefix are not enough for using your own S3 bucket. Could be wrong tho.

One thing I often overlook is remembering to checkout all the git submodules for things like the VPC Quick Start.
eg:
> git submodule update --init --recursive

Then ensure submodules/ is also copied to the same S3 bucket

For a much better experience with developing/customizing Quick Starts take a look at [taskcat](https://github.com/aws-quickstart/taskcat).

**Comment by gargana** [comment]
Have updated support for newer versions. Will continue working the individual items in their own issues #25 #26 #27 #28 #29. Closing this out for now.

**Comment by jagibson** [comment]
Awesome!  I'm using a homebrew method for ECS right now so I know know if I'll circle back to this or not but it's good to hear.
