### ISSUE TITLE
Fails to start on 4.0.0

### ISSUE THREAD

**Issue by calvinbui** [aws-quickstart/quickstart-awx#23]
Everything is deployed but the `awx` container runs into the error:

```
raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
```

Which leads to the container and task definition being stopped by the load balancer health check.

Similar issues 
https://github.com/geerlingguy/awx-container/issues/46
https://github.com/ansible/awx/issues/3554

**Comment by gargana** [comment]
Thanks for pointing this out I am taking a look at it.

**Comment by calvinbui** [comment]
any updates?

**Comment by ajgargan** [comment]
Hi @calvinbui I am still looking into this will provide an update here.

**Comment by gargana** [comment]
After a bit of digging I notices that from 4.X the containers are expecting files on the underlying host which are created by the ansible playbooks.
Previously dynamic bits have been injected into the containers via ENV.
--- snip from the awxweb container ---
"HostConfig": {
"Binds": [
"/tmp/awxcompose/credentials.py:/etc/tower/conf.d/credentials.py:rw",
"/tmp/awxcompose/SECRET_KEY:/etc/tower/SECRET_KEY:rw",
"/tmp/awxcompose/environment.sh:/etc/tower/conf.d/environment.sh:rw"
],
--- snip ---

This is going to take a bit of redesign to implement.

**Comment by neilalexander** [comment]
This also appears to be an issue in the 5.0.0 image.

**Comment by sblack4** [comment]
and the 6.0.0 image

**Comment by sblack4** [comment]
You can make the containers pull the secret from the environment by altering the function at the top of `/etc/tower/settings.py`. I also wanted to run AWX on ECS and created some friendlier containers here: https://github.com/sblack4/awx_containers

**Comment by calvinbui** [comment]
thanks for the fix, but i still can't deploy the `develop` branch they were merged into. The master template is pulling the `awx-workload.template` file from the `aws-quickstart` S3 bucket.

**Comment by gargana** [comment]
@calvinbui these changes should now be merged in to the master branch and master S3 buckets.
