### ISSUE TITLE
Unable to save System Settings - Websockets Not Working

### ISSUE THREAD

**Issue by ckizziar** [aws-quickstart/quickstart-awx#3]
**ISSUE TYPE**
Bug Report

**COMPONENT NAME**
Websockets

**SUMMARY**
When attempting to update the base URL of the tower host and remote host headers (precursors to SAML config) the page shows saving, however after navigating to another page and going back to system settings the changes are not saved. Browser console shows continuous error connecting to websocket. Updating these settings via the API also fails with the message "A server error has occurred."

**ENVIRONMENT**
AWX version: 1.0.6.16
AWX install method: AWS-Quickstart
Ansible version: 2.5.4
Web Browser: Chrome and Firefox

**STEPS TO REPRODUCE**
Navigate to Settings > System and try to update the tower host base URL or remote host headers. Navigate to a different page, and back to system settings.

**EXPECTED RESULTS**
Settings should have been saved.

**ACTUAL RESULTS**
Settings have reverted to previous values. Web console shows continuous message "Firefox can’t establish a connection to the server at ws://albname.us-east-1.elb.amazonaws.com/websocket/."
Console also reports the following:

`TypeError
columnNumber: 858885
fileName: "http://albname.us-east-1.elb.amazonaws.com/static/js/app.59bb2467807cad88b7cb.js"
lineNumber: 42
message: "data is undefined"
stack: "exports.default</<@http://albname.us-east-1.elb.amazonaws.com/static/js/app.59bb2467807cad88b7cb.js:42:858885\nformSave/<@http://albname.us-east-1.elb.amazonaws.com/static/js/app.59bb2467807cad88b7cb.js:42:459584\nprocessQueue@http://albname.us-east-1.elb.amazonaws.com/static/js/vendor.df1e14afc0faea10fa99.js:583:134656\nscheduleProcessQueue/<@http://albname.us-east-1.elb.amazonaws.com/static/js/vendor.df1e14afc0faea10fa99.js:583:135605\n$digest@http://albname.us-east-1.elb.amazonaws.com/static/js/vendor.df1e14afc0faea10fa99.js:583:146521\n$apply@http://albname.us-east-1.elb.amazonaws.com/static/js/vendor.df1e14afc0faea10fa99.js:583:149463\ndone@http://albname.us-east-1.elb.amazonaws.com/static/js/vendor.df1e14afc0faea10fa99.js:583:101267\ncompleteRequest@http://albname.us-east-1.elb.amazonaws.com/static/js/vendor.df1e14afc0faea10fa99.js:583:106296\ncreateHttpBackend/</xhr.onload@http://albname.us-east-1.elb.amazonaws.com/static/js/vendor.df1e14afc0faea10fa99.js:583:107075\n"
__proto__: {…}
constructor: function TypeError()
message: ""
name: "TypeError"
stack: ""
__proto__: Object { … }
 Possibly unhandled rejection: {}`

**Comment by avattathil** [comment]
@gargana can you take a look please?

**Comment by gargana** [comment]
Hi Tony

Have been looking at this.

From my testing this appears to be and AWX issue. Have done some recreation of the environment outside of ECS and the QuickStart and receive the same issue.

Not sure about next steps here. Am looking at the AWX project to find any open issues relating to this and also trying to find a workaround.

Not sure about public comms with issues on quickstarts. Is there any form of guideline around these?

Regards

Andrew Gargan | Cloud Support Engineer

**Comment by smonfort-cacd2** [comment]
Facing the same issue here on a fresh deployment of the Cloudformation stack : can not update system settings due to websocket connection issue.

**Comment by ajgargan** [comment]
Thanks @ckizziar for bringing this to our attention.

There are two actual issues which are:
Websocket issue which I have managed to resolve to the point of hitting this upstream issue: https://github.com/ansible/awx/issues/1861

And the issue of not being able to save config which seems, from my investigations so far, awx related. I have not been able to get this functionality working for any standalone deployments of awx containers.

Still investigating both issues and working on next steps.

**Comment by gargana** [comment]
Saving of configuration appears to have been fixed upstream in the new container images from dockerhub.
https://hub.docker.com/r/ansible/awx_task/ - 1.0.6.35
https://hub.docker.com/r/ansible/awx_web/ - 1.0.6.35

Am still working on resolving the websocket issue.

**Comment by gargana** [comment]
I am marking this issue as resolved.
