### ISSUE TITLE
Template fails with "failed to create: [InfrastructureStack]"

### ISSUE THREAD

**Issue by robertgates55** [aws-quickstart/quickstart-awx#32]
Am getting a rather unhelpful "Template fails with "failed to create: [InfrastructureStack]" error in cloudformation. Is there any way of getting additional debug info?

Any ideas on how to proceed?

2019-09-28 13:20:29 UTC+0100 | WorkloadStack | CREATE_FAILED | Embedded stack arn:aws:cloudformation:eu-west-1:986315960982:stack/AWX-WorkloadStack-1IUIIHARJCSL0/fda5ec90-e1e9-11e9-a1f7-02135cc8443e was not successfully created: The following resource(s) failed to create: [InfrastructureStack].
-- | -- | -- | --
2019-09-28 13:17:51 UTC+0100 | WorkloadStack | CREATE_IN_PROGRESS | Resource creation Initiated
2019-09-28 13:17:50 UTC+0100 | WorkloadStack | CREATE_IN_PROGRESS | -
2019-09-28 13:17:47 UTC+0100 | VPCStack | CREATE_COMPLETE | -
2019-09-28 13:14:44 UTC+0100 | VPCStack | CREATE_IN_PROGRESS | Resource creation Initiated
2019-09-28 13:14:42 UTC+0100 | VPCStack | CREATE_IN_PROGRESS | -
2019-09-28 13:14:38 UTC+0100 | AWX | CREATE_IN_PROGRESS | User Initiated

**Comment by gargana** [comment]
Hey Robert, when a nested CloudFormation stack fails you will need to look at that stack to find the failure reason. In this case you actually want to look at the stack which failed to launch being : arn:aws:cloudformation:eu-west-1:986315960982:stack/AWX-WorkloadStack-1IUIIHARJCSL0/fda5ec90-e1e9-11e9-a1f7-02135cc8443e. To see deleted/failed stacks you will need to change the filter on the stacks page within the CloudFormation console.

This link should take you to the stack in the console and should give you a better idea of the failure:
https://console.aws.amazon.com/cloudformation/home?region=eu-west-1#/stack/detail?stackId=arn:aws:cloudformation:eu-west-1:986315960982:stack/AWX-WorkloadStack-1IUIIHARJCSL0/fda5ec90-e1e9-11e9-a1f7-02135cc8443e

Hope that helps.

*As an aside I would advise against posting full ARNs on github posts

**Comment by gargana** [comment]
After further investigation I have found that an update to the Lambda platform is causing the Build of containers to fail for the Lambda backed custom resource in this QuickStart. 

To see if you are affected by the same you can take a look in the CloudWatch logs for the lambda function execution: https://console.aws.amazon.com/cloudwatch/home?logEventViewer:group=/aws/lambda/**YOURSTACKNAME**-WorkloadStack-**15XXXXXX**-BuildContainersLambda-**HXYXYXYXYX**
The error is: "An HTTP Client raised and unhandled exception: 'requestid'"

I have filed and issue with the boto3 project here: https://github.com/boto/boto3/issues/2155


Am working on a fix to ensure a working version of boto3/botocore are shipped with this Lambda function.

To see details of the workaround I am going to implement see the above issue.

**Comment by bwboy** [comment]
I meet the same problem...when I build it on Virginia.

**Comment by gargana** [comment]
Thanks for your patience here. It turns out the way I was configuring mainlogger is what broke with the newer version of botocore/boto3. I have refactored the Lambda function to python 3.7 and changed the logging behavior which should avoid this kind of issue going forward.

**Comment by gargana** [comment]
Closing this issue out.
