### ISSUE TITLE
AWXStack Template fails with "failed to create: BuildContainers "

### ISSUE THREAD

**Issue by lulu1993cooly** [aws-quickstart/quickstart-awx#33]
The AWXStack fails on the Lambda function for the BuildContainers resource with a runtime error. It seems that a recent Lambda boto3 and botocore update broke this function.

I was able to get this stack to create by creating a deployment package with boto3 1.7 and botocore 1.11.0. I am not sure what version specifically breaks the functionality.

**Comment by gargana** [comment]
This relates to #32 I should have a fix out for this shortly.

**Comment by gargana** [comment]
This issue was to do with the way in which I was formatting the mainlogger. I removed the log formatting to avoid this kind of issue going forward.
