### ISSUE TITLE
deploy to existing vpc

### ISSUE THREAD

**Issue by cbnorman** [aws-quickstart/quickstart-awx#8]
ive been trying to run this quick start agianst an existing vpc as its already peered to the other vpcs i would like awx running playbooks agianst. when i try and create in the existing vpc it fails on attaching an internet gateway i think because i already have one attached. is it possible to configure this stack in an existing vpc?

**Comment by jaggaer-zsmith** [comment]
Agreed, I am not familiar with CloudFormation and it would be nice to have option to deploy to existing infrastructure. I literally just chatted with AWS support about the effects of cloudformation on existing infrastructure

**Comment by gargana** [comment]
I am giving this my full attention at the moment.

**Comment by jaggaer-zsmith** [comment]
@gargana THANK YOU!

**Comment by gargana** [comment]
The deployment guide has been updated with the details around launching into an existing VPC. 
See: https://aws.amazon.com/quickstart/architecture/awx/
